export const minification_options = {
	collapseWhitespace: true, // Сжимает пробелы, которые составляют текстовые узлы, делая HTML компактнее
	removeComments: true, // Удаляет комментарии HTML, что уменьшает размер файла
	removeRedundantAttributes: true, // Удаляет атрибуты, когда их значение совпадает со значением по умолчанию
	removeScriptTypeAttributes: true, // Удаляет 'type="text/javascript"' из тегов 'script', так как это не нужно для современных браузеров
	removeStyleLinkTypeAttributes: true, // Удаляет 'type="text/css"' из тегов 'style' и 'link', так как это не нужно для современных браузеров
	useShortDoctype: true, // Заменяет 'doctype' на короткий (HTML5) doctype, который короче и более современный
	minifyCSS: true, // Сжимает CSS в элементах 'style' и атрибутах 'style' (использует 'clean-css')
	minifyJS: true, // Сжимает JavaScript в элементах 'script' и атрибутах событий (использует 'UglifyJS')
	removeAttributeQuotes: true, // Удаляет кавычки вокруг атрибутов, когда это возможно
	sortAttributes: true, // Сортирует атрибуты по частоте использования
	sortClassName: true, // Сортирует классы стилей по частоте использования

	// Отключенные настройки
	// caseSensitive: false, // Не включено, потому что большинство веб-разработчиков не используют чувствительные к регистру атрибуты
	// collapseBooleanAttributes: false, // Не включено, чтобы сохранить ясность кода и совместимость с различными браузерами
	// collapseInlineTagWhitespace: false, // Не включено, так как может вызвать проблемы с отображением элементов в некоторых случаях
	// conservativeCollapse: false, // Не включено, так как collapseWhitespace уже обеспечивает достаточную минификацию пробелов
	// continueOnParseError: false, // Не включено, чтобы разработчик мог заметить и исправить ошибки разбора
	// customAttrAssign: [], // Не включено, так как большинство сайтов не используют пользовательские атрибуты
	// customAttrCollapse: null, // Не включено, так как большинство сайтов не используют пользовательские атрибуты
	// customAttrSurround: [], // Не включено, так как большинство сайтов не используют пользовательские атрибуты
	// customEventAttributes: [/^on[a-z]{3,}$/], // Не включено, так как обработка пользовательских событий может нарушить работу приложения
	// decodeEntities: false, // Не включено, чтобы сохранить совместимость с различными браузерами и устройствами
	// ignoreCustomComments: [/^!/], // Не включено, так как большинство сайтов не используют пользовательские комментарии
	// ignoreCustomFragments: false, // Необходимо сохранять все пользовательские фрагменты
	// includeAutoGeneratedTags: false, // Не нужно включать автоматически сгенерированные теги
	// keepClosingSlash: false, // Не нужно сохранять закрывающий слеш на одиночных элементах
	// maxLineLength: false, // Не нужно ограничивать максимальную длину строки
};
export const pocket = {
	url: "http://127.0.0.1:8090"
}